"$schema" = 'https://starship.rs/config-schema.json'
palette = "kanagawa_dragon"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "aqua"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](orange) ($ahead_behind$stashed)]($style)"
style = "blue"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "grey1"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "grey1"
detect_extensions = []
detect_files = []

[palettes.kanagawa_dragon]
bg0 = "#181616"
bg1 = "#0D0C0C"
bg2 = "#12120F"
bg3 = "#2D4F67"
fg = "#C5C9C5"
red = "#C4746E"
orange = "#B98D7B"
yellow = "#C4B28A"
green = "#8A9A7B"
aqua = "#8EA4A2"
blue = "#8BA4B0"
purple = "#A292A3"
grey0 = "#A6A69C"
grey1 = "#C8C093"
grey2 = "#C5C9C5"
statusline1 = "#8A9A7B"
statusline2 = "#C5C9C5"
statusline3 = "#C4746E"
