set -g status on
set -g status-interval 2
set -g status-style "fg=#e0def4,bg=#191724"
set -g status-left-style "fg=#e0def4,bg=#191724"
set -g status-right-style "fg=#e0def4,bg=#191724"
set -g message-style "fg=#eb6f92,bg=#191724"
set -g message-command-style "fg=#e0def4,bg=#26233a"
set -g mode-style "fg=#e0def4,bg=#403d52"
setw -g window-status-style "fg=#908caa,bg=#191724"
setw -g window-status-activity-style "fg=#f6c177,bg=#191724"
setw -g window-status-current-style "fg=#e0def4,bg=#403d52,bold"
set -g pane-border-style "fg=#26233a"
set -g pane-active-border-style "fg=#9ccfd8"
set -g display-panes-active-colour '#9ccfd8'
set -g display-panes-colour '#f6c177'
set -g clock-mode-colour '#9ccfd8'
set -g window-status-bell-style "fg=#191724,bg=#eb6f92"

set -g status-left-length 60
set -g status-right-length 150
set -g status-left "#[fg=#f6c177,bg=#191724,bold] #S #[fg=#403d52,nobold]|#[fg=#908caa] #(whoami) "
set -g status-right "#[fg=#908caa,bg=#191724] %Y-%m-%d %H:%M #[fg=#403d52]|#[fg=#9ccfd8,bold] #h "
set -g window-status-separator " "
set -g window-status-format "#[fg=#908caa,bg=#191724] #I:#W "
set -g window-status-current-format "#[fg=#e0def4,bg=#403d52,bold] #I:#W "
