set -g status on
set -g status-interval 2
set -g status-style "fg=#575279,bg=#faf4ed"
set -g status-left-style "fg=#575279,bg=#faf4ed"
set -g status-right-style "fg=#575279,bg=#faf4ed"
set -g message-style "fg=#b4637a,bg=#faf4ed"
set -g message-command-style "fg=#575279,bg=#f2e9e1"
set -g mode-style "fg=#575279,bg=#dfdad9"
setw -g window-status-style "fg=#797593,bg=#faf4ed"
setw -g window-status-activity-style "fg=#ea9d34,bg=#faf4ed"
setw -g window-status-current-style "fg=#575279,bg=#dfdad9,bold"
set -g pane-border-style "fg=#f2e9e1"
set -g pane-active-border-style "fg=#56949f"
set -g display-panes-active-colour '#56949f'
set -g display-panes-colour '#ea9d34'
set -g clock-mode-colour '#56949f'
set -g window-status-bell-style "fg=#faf4ed,bg=#b4637a"

set -g status-left-length 60
set -g status-right-length 150
set -g status-left "#[fg=#ea9d34,bg=#faf4ed,bold] #S #[fg=#dfdad9,nobold]|#[fg=#797593] #(whoami) "
set -g status-right "#[fg=#797593,bg=#faf4ed] %Y-%m-%d %H:%M #[fg=#dfdad9]|#[fg=#56949f,bold] #h "
set -g window-status-separator " "
set -g window-status-format "#[fg=#797593,bg=#faf4ed] #I:#W "
set -g window-status-current-format "#[fg=#575279,bg=#dfdad9,bold] #I:#W "
